### ISSUE TITLE
User having issues with async handlers

### ISSUE THREAD

**Issue by lol768** [KittehOrg/KittehIRCClientLib#101]
```
Exception in thread "main" java.lang.RuntimeException: net.engio.mbassy.bus.error.MessageBusException: net.engio.mbassy.bus.error.MissingPropertyException: The property bus.handlers.async-executor is not available in this runtime
    at net.engio.mbassy.subscription.SubscriptionManager.subscribe(SubscriptionManager.java:126)
    at net.engio.mbassy.bus.AbstractPubSubSupport.subscribe(AbstractPubSubSupport.java:74)
    at org.kitteh.irc.client.library.implementation.ManagerEvent.registerEventListener(ManagerEvent.java:91)
    at org.kitteh.irc.client.library.myBot.main(myBot.java:1375)
Caused by: net.engio.mbassy.bus.error.MessageBusException: net.engio.mbassy.bus.error.MissingPropertyException: The property bus.handlers.async-executor is not available in this runtime
    at net.engio.mbassy.subscription.SubscriptionFactory.createSubscription(SubscriptionFactory.java:32)
    at net.engio.mbassy.subscription.SubscriptionManager.subscribe(SubscriptionManager.java:112)
    ... 3 more
Caused by: net.engio.mbassy.bus.error.MissingPropertyException: The property bus.handlers.async-executor is not available in this runtime
    at net.engio.mbassy.bus.BusRuntime.get(BusRuntime.java:33)
    at net.engio.mbassy.dispatch.AsynchronousHandlerInvocation.<init>(AsynchronousHandlerInvocation.java:23)
    at net.engio.mbassy.subscription.SubscriptionFactory.buildInvocationForHandler(SubscriptionFactory.java:42)
    at net.engio.mbassy.subscription.SubscriptionFactory.createSubscription(SubscriptionFactory.java:26)

        ... 4 more

```

**Comment by mbax** [comment]
TODO: Investigate whether or not I can just safely add `Feature.AsynchronousHandlerInvocation` to the message bus. Also will require changing from `SyncMessageBus` to `MBassador` but I don't think that will actually affect anything itself.

**Comment by mbax** [comment]
https://github.com/KittehOrg/KittehIRCClientLib/commit/378c3af6e6de83d73aedaab89cbfeb733448965c
