### ISSUE TITLE
SIOOBE on capability manager

### ISSUE THREAD

**Issue by kashike** [KittehOrg/KittehIRCClientLib#127]
```
[17:06:31] [IRCClient] [Kitteh IRC Client Listener (freenode)/DEBUG]: < :irc.znc.in CAP Korobi ACK :
[17:06:31] [IRCClient] [Kitteh IRC Client Listener (freenode)/ERROR]: Client Exception
org.kitteh.irc.client.library.exception.KittehEventException: java.lang.reflect.InvocationTargetException
        at org.kitteh.irc.client.library.implementation.ManagerEvent$Exceptional.handleError(ManagerEvent.java:75) ~[felix-2.0.0-SNAPSHOT-0717-2.jar:2.0.0-SNAPSHOT-0a0c56d]
        at org.kitteh.irc.lib.net.engio.mbassy.subscription.SubscriptionContext.handleError(SubscriptionContext.java:59) ~[felix-2.0.0-SNAPSHOT-0717-2.jar:2.0.0-SNAPSHOT-0a0c56d]
        at org.kitteh.irc.lib.net.engio.mbassy.dispatch.HandlerInvocation.handlePublicationError(HandlerInvocation.java:24) ~[felix-2.0.0-SNAPSHOT-0717-2.jar:2.0.0-SNAPSHOT-0a0c56d]
        at org.kitteh.irc.lib.net.engio.mbassy.dispatch.ReflectiveHandlerInvocation.invokeHandler(ReflectiveHandlerInvocation.java:34) ~[felix-2.0.0-SNAPSHOT-0717-2.jar:2.0.0-SNAPSHOT-0a0c56d]
        at org.kitteh.irc.lib.net.engio.mbassy.dispatch.ReflectiveHandlerInvocation.invoke(ReflectiveHandlerInvocation.java:49) ~[felix-2.0.0-SNAPSHOT-0717-2.jar:2.0.0-SNAPSHOT-0a0c56d]
        at org.kitteh.irc.lib.net.engio.mbassy.dispatch.MessageDispatcher.dispatch(MessageDispatcher.java:30) ~[felix-2.0.0-SNAPSHOT-0717-2.jar:2.0.0-SNAPSHOT-0a0c56d]
        at org.kitteh.irc.lib.net.engio.mbassy.dispatch.FilteredMessageDispatcher.dispatch(FilteredMessageDispatcher.java:41) ~[felix-2.0.0-SNAPSHOT-0717-2.jar:2.0.0-SNAPSHOT-0a0c56d]
        at org.kitteh.irc.client.library.implementation.ManagerEvent$FilteredMessageDispatcher.dispatch(ManagerEvent.java:125) ~[felix-2.0.0-SNAPSHOT-0717-2.jar:2.0.0-SNAPSHOT-0a0c56d]
        at org.kitteh.irc.lib.net.engio.mbassy.subscription.Subscription.publish(Subscription.java:71) ~[felix-2.0.0-SNAPSHOT-0717-2.jar:2.0.0-SNAPSHOT-0a0c56d]
        at org.kitteh.irc.lib.net.engio.mbassy.bus.MessagePublication.execute(MessagePublication.java:46) ~[felix-2.0.0-SNAPSHOT-0717-2.jar:2.0.0-SNAPSHOT-0a0c56d]
        at org.kitteh.irc.lib.net.engio.mbassy.bus.MBassador.publish(MBassador.java:70) ~[felix-2.0.0-SNAPSHOT-0717-2.jar:2.0.0-SNAPSHOT-0a0c56d]
        at org.kitteh.irc.client.library.implementation.ManagerEvent.callEvent(ManagerEvent.java:175) ~[felix-2.0.0-SNAPSHOT-0717-2.jar:2.0.0-SNAPSHOT-0a0c56d]
        at org.kitteh.irc.client.library.implementation.IRCClient.handleLine(IRCClient.java:632) ~[felix-2.0.0-SNAPSHOT-0717-2.jar:2.0.0-SNAPSHOT-0a0c56d]
        at org.kitteh.irc.client.library.implementation.IRCClient.access$000(IRCClient.java:60) ~[felix-2.0.0-SNAPSHOT-0717-2.jar:2.0.0-SNAPSHOT-0a0c56d]
        at org.kitteh.irc.client.library.implementation.IRCClient$InputProcessor.processElement(IRCClient.java:69) ~[felix-2.0.0-SNAPSHOT-0717-2.jar:2.0.0-SNAPSHOT-0a0c56d]
        at org.kitteh.irc.client.library.implementation.IRCClient$InputProcessor.processElement(IRCClient.java:61) ~[felix-2.0.0-SNAPSHOT-0717-2.jar:2.0.0-SNAPSHOT-0a0c56d]
        at org.kitteh.irc.client.library.util.QueueProcessingThread.run(QueueProcessingThread.java:60) [felix-2.0.0-SNAPSHOT-0717-2.jar:2.0.0-SNAPSHOT-0a0c56d]
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
        at org.kitteh.irc.lib.net.engio.mbassy.dispatch.ReflectiveHandlerInvocation.invokeHandler(ReflectiveHandlerInvocation.java:23) ~[felix-2.0.0-SNAPSHOT-0717-2.jar:2.0.0-SNAPSHOT-0a0c56d]
        ... 13 more
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
        at java.lang.String.charAt(String.java:658) ~[?:1.8.0_91]
        at org.kitteh.irc.client.library.implementation.ManagerCapability$IRCCapabilityState.<init>(ManagerCapability.java:49) ~[felix-2.0.0-SNAPSHOT-0717-2.jar:2.0.0-SNAPSHOT-0a0c56d]
        at org.kitteh.irc.client.library.implementation.EventListener.lambda$cap$54(EventListener.java:629) ~[felix-2.0.0-SNAPSHOT-0717-2.jar:2.0.0-SNAPSHOT-0a0c56d]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_91]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_91]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_91]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_91]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_91]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_91]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_91]
        at org.kitteh.irc.client.library.implementation.EventListener.cap(EventListener.java:629) ~[felix-2.0.0-SNAPSHOT-0717-2.jar:2.0.0-SNAPSHOT-0a0c56d]
        at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
        at org.kitteh.irc.lib.net.engio.mbassy.dispatch.ReflectiveHandlerInvocation.invokeHandler(ReflectiveHandlerInvocation.java:23) ~[felix-2.0.0-SNAPSHOT-0717-2.jar:2.0.0-SNAPSHOT-0a0c56d]
        ... 13 more
```

**Comment by mbax** [comment]
Well played, znc

https://github.com/KittehOrg/KittehIRCClientLib/commit/d9dfc52dc30ba57b51853ff17f86eecb64cd758a
