### ISSUE TITLE
IRCServerSnapshot cannot be cast to User

### ISSUE THREAD

**Issue by kashike** [KittehOrg/KittehIRCClientLib#184]
```
Caused by: java.lang.ClassCastException: org.kitteh.irc.client.library.implementation.ActorProvider$IRCServerSnapshot cannot be cast to org.kitteh.irc.client.library.element.User
        at org.kitteh.irc.client.library.implementation.EventListener.kick(EventListener.java:1136) ~[felix-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT-e45a3bb]
        at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
        at net.engio.mbassy.dispatch.ReflectiveHandlerInvocation.invokeHandler(ReflectiveHandlerInvocation.java:23) ~[felix-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT-e45a3bb]
```

https://github.com/KittehOrg/KittehIRCClientLib/blob/master/src/main/java/org/kitteh/irc/client/library/implementation/EventListener.java#L1136

**Comment by mbax** [comment]
Good to know the server itself can kick. Marking as patch until I realize oh god it's going to be breaking later.

**Comment by mbax** [comment]
https://github.com/KittehOrg/KittehIRCClientLib/commit/43f960e902ec73ee4782150cbc29f13057b4e4a0

Actually supporting this will require a breaking change. ._.

**Comment by Zarthus** [comment]
Servers will do a lot of actions when it is trying to resynchronize after a netsplit.

**Comment by mbax** [comment]
https://github.com/KittehOrg/KittehIRCClientLib/commit/2a6a7725b8e20e63cda41ba5ba70b8fa84a01821
