### ISSUE TITLE
Group already set.

### ISSUE THREAD

**Issue by mbax** [KittehOrg/KittehIRCClientLib#23]
```
java.lang.IllegalStateException: group set already
at org.kitteh.irc.lib.io.netty.bootstrap.AbstractBootstrap.group(AbstractBootstrap.java:83)
at org.kitteh.irc.client.library.NettyManager.connect(NettyManager.java:230)
```

**Comment by mbax** [comment]
https://github.com/KittehOrg/KittehIRCClientLib/commit/828dadd8d4d7a8bd743e5da17f1f73ad53406358
