### ISSUE TITLE
exception in getting start

### ISSUE THREAD

**Issue by sourena21** [KittehOrg/KittehIRCClientLib#249]
hi
i am getting start with your lib and its ducument to use irc but got an exception.
i add this codes in onCreate methos in mainactivity to connect to server:

    Client client = Client.builder().nick("MyNickName").server().
        host("myserveraddress").then().buildAndConnect();
    client.addChannel("#myChannel");
    client.sendMessage("#myChannel", "Hello World!");

and exception text is:

 FATAL EXCEPTION: AsyncTask #1
    java.lang.RuntimeException: An error occured while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:299)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
        at java.util.concurrent.FutureTask.run(FutureTask.java:239)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
        at java.lang.Thread.run(Thread.java:841)
     Caused by: java.lang.NoClassDefFoundError: org.kitteh.irc.client.library.defaults.-$$Lambda$AATLo-Xke91lEYJvwj0ou5zrtEM
        at org.kitteh.irc.client.library.defaults.DefaultBuilder.<clinit>(DefaultBuilder.java:312)
        at org.kitteh.irc.client.library.Client$-CC.builder(Client.java:931)
        at android.hseify69.ir.testirc.utils.HelloKitteh.main(HelloKitteh.java:12)
        at android.hseify69.ir.testirc.activities.MainActivity$StartKitteh.doInBackground(MainActivity.java:80)
        at android.hseify69.ir.testirc.activities.MainActivity$StartKitteh.doInBackground(MainActivity.java:75)
        at android.os.AsyncTask$2.call(AsyncTask.java:287)
        at java.util.concurrent.FutureTask.run(FutureTask.java:234)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573) 
        at java.lang.Thread.run(Thread.java:841) 

what i must to do? and what error is that?

**Comment by Zarthus** [comment]
My theory (and I could have dated knowledge) is that you're running this on Android, and Android doesn't support lambdas yet.

**Comment by sourena21** [comment]
yes you are right
but i thoght this library is for android apps.
witch library i must use?
@Zarthus

**Comment by lol768** [comment]
What's your `minSdkVersion` @sourena21 ?

**Comment by bendem** [comment]
related #217 and #206

**Comment by lol768** [comment]
https://github.com/KittehOrg/KittehIRCClientLib/pull/250

**Comment by Zarthus** [comment]
@sourena21 please go through http://kicl.kitteh.org/en/latest/android/ and let us know if it works.

**Comment by mbax** [comment]
I'm going to close this, but feel free to respond here for more discussion!
